In [1]:
%load_ext sql

In [2]:
%env DATABASE_URL=postgresql://sms_user:sms_password@localhost:5432/sms_db

env: DATABASE_URL=postgresql://sms_user:sms_password@localhost:5432/sms_db

In [8]:
%sql SELECT * FROM information_schema.tables LIMIT 20

 * postgresql://sms_user:***@localhost:5432/sms_db
20 rows affected.

[('sms_db', 'public', 'users', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('sms_db', 'pg_catalog', 'pg_type', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('sms_db', 'pg_catalog', 'pg_foreign_table', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('sms_db', 'pg_catalog', 'pg_roles', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('sms_db', 'pg_catalog', 'pg_settings', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('sms_db', 'pg_catalog', 'pg_available_extension_versions', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('sms_db', 'pg_catalog', 'pg_stat_xact_user_functions', 'VIEW', None, None, None, None, None, 'NO', 'NO', None),
 ('sms_db', 'pg_catalog', 'pg_subscription', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('sms_db', 'pg_catalog', 'pg_attribute', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('sms_db', 'pg_catalog', 'pg_proc', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('sms_db', 'pg_catalog', 'pg_class', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('sms_db', 'pg_catalog', 'pg_attrdef', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('sms_db', 'pg_catalog', 'pg_constraint', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('sms_db', 'pg_catalog', 'pg_inherits', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('sms_db', 'pg_catalog', 'pg_index', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('sms_db', 'pg_catalog', 'pg_operator', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('sms_db', 'pg_catalog', 'pg_opfamily', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('sms_db', 'pg_catalog', 'pg_opclass', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('sms_db', 'pg_catalog', 'pg_am', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('sms_db', 'pg_catalog', 'pg_amop', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None)]

In [4]:
%sql DROP TABLE IF EXISTS users

 * postgresql://sms_user:***@localhost:5432/sms_db
Done.

[]

In [5]:
%%sql result_set <<

CREATE TABLE users (
  user_id SERIAL PRIMARY KEY,
  user_first_name VARCHAR(30) NOT NULL,
  user_last_name VARCHAR(30) NOT NULL,
  user_email_id VARCHAR(50) NOT NULL,
  user_email_validated BOOLEAN DEFAULT FALSE,
  user_password VARCHAR(200),
  user_role VARCHAR(1) NOT NULL DEFAULT 'U', --U and A
  is_active BOOLEAN DEFAULT FALSE,
  created_dt DATE DEFAULT CURRENT_DATE,
  last_updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

 * postgresql://sms_user:***@localhost:5432/sms_db
Done.
Returning data to local variable result_set

In [6]:
%%sql result_set <<

SELECT * 
FROM information_schema.tables 
WHERE table_name = 'users'

 * postgresql://sms_user:***@localhost:5432/sms_db
1 rows affected.
Returning data to local variable result_set

In [7]:
display(result_set)

[('sms_db', 'public', 'users', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None)]